networks:
  monitoring:
    driver: bridge

services:
  otel-collector:
      image: otel/opentelemetry-collector-contrib:latest
      container_name: otel-collector
      # Mount the collector's configuration file
      volumes:
        - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      # Use the command to start the collector with your specific config file
      command: ["--config=/etc/otel-collector-config.yml"]
      # Ports for various OTLP receivers (required for sending data to the collector)
      ports:
        - "4317:4317" # OTLP gRPC receiver
        - "4318:4318" # OTLP HTTP receiver
      networks:
        - monitoring
      depends_on:
        - prometheus # Ensure Prometheus is running for the collector to send metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-otlp-receiver'          # required for Gaia
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  grafana-data: